export const getTickers = async ({
  limit,
  page,
  query,
}: {
  limit?: number;
  page?: number;
  query?: string;
}) => {
  if (typeof query === 'string' && query.includes('micro')) {
    return {
      pagination: {
        limit: 100,
        offset: 0,
        count: 16,
        total: 16,
      },
      data: [
        {
          name: 'Microsoft Corporation',
          symbol: 'MSFT',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'MICROSOFT DRN',
          symbol: 'MSFT34.BVMF',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'B3 - Brasil Bolsa Balcão S.A',
            acronym: 'Bovespa',
            mic: 'BVMF',
            country: 'Brazil',
            country_code: 'BR',
            city: 'Sao Paulo',
            website: 'www.bmfbovespa.com.br',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFT.XSGO',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Santiago Stock Exchange',
            acronym: 'BVS',
            mic: 'XSGO',
            country: 'Chile',
            country_code: 'CL',
            city: 'Santiago',
            website: 'www.bolsadesantiago.com',
          },
        },
        {
          name: 'MICROSOFT CORP. REGISTERED SHARES DL-,00000625',
          symbol: 'MSF.XSTU',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Börse Stuttgart',
            acronym: 'XSTU',
            mic: 'XSTU',
            country: 'Germany',
            country_code: 'DE',
            city: 'Stuttgart',
            website: 'www.boerse-stuttgart.de',
          },
        },
        {
          name: 'MICROSOFT DL-,00000625',
          symbol: 'MSF.XETRA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Deutsche Börse Xetra',
            acronym: 'XETR',
            mic: 'XETRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: '',
          },
        },
        {
          name: 'MICROSOFT DL-,00000625',
          symbol: 'MSF.XFRA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Deutsche Börse',
            acronym: 'FSX',
            mic: 'XFRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: 'www.deutsche-boerse.com',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFT.XMIL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Borsa Italiana',
            acronym: 'MIL',
            mic: 'XMIL',
            country: 'Italy',
            country_code: 'IT',
            city: 'Milano',
            website: 'www.borsaitaliana.it',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFT.XMEX',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Mexican Stock Exchange',
            acronym: 'BMV',
            mic: 'XMEX',
            country: 'Mexico',
            country_code: 'MX',
            city: 'Mexico City',
            website: 'www.bmv.com.mx',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFT.XBUE',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Buenos Aires Stock Exchange',
            acronym: 'BCBA',
            mic: 'XBUE',
            country: 'Argentina',
            country_code: 'AR',
            city: 'Buenos Aires',
            website: 'www.bcba.sba.com.ar',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFTD.XBUE',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Buenos Aires Stock Exchange',
            acronym: 'BCBA',
            mic: 'XBUE',
            country: 'Argentina',
            country_code: 'AR',
            city: 'Buenos Aires',
            website: 'www.bcba.sba.com.ar',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFT',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Microsoft Corporation',
          symbol: '0QYP.XLON',
          has_intraday: false,
          has_eod: true,
          country: 'UK',
          stock_exchange: {
            name: 'London Stock Exchange',
            acronym: 'LSE',
            mic: 'XLON',
            country: 'United Kingdom',
            country_code: 'GB',
            city: 'London',
            website: 'www.londonstockexchange.com',
          },
        },
        {
          name: 'MICROSOFT CORP. CDR',
          symbol: 'MSF0.XFRA',
          has_intraday: false,
          has_eod: true,
          country: 'Germany',
          stock_exchange: {
            name: 'Deutsche Börse',
            acronym: 'FSX',
            mic: 'XFRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: 'www.deutsche-boerse.com',
          },
        },
        {
          name: 'MICROSOFT DRN',
          symbol: 'MSFT34',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'MICROSOFT CORP',
          symbol: 'MSFTD',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Microsoft Corp.',
          symbol: '1MSFT.XMIL',
          has_intraday: false,
          has_eod: true,
          country: 'Italy',
          stock_exchange: {
            name: 'Borsa Italiana',
            acronym: 'MIL',
            mic: 'XMIL',
            country: 'Italy',
            country_code: 'IT',
            city: 'Milano',
            website: 'www.borsaitaliana.it',
          },
        },
      ],
    };
  }

  if (typeof query === 'string' && query.includes('apple'))
    return {
      pagination: {
        limit: 100,
        offset: 0,
        count: 30,
        total: 30,
      },
      data: [
        {
          name: 'Apple Inc',
          symbol: 'AAPL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'APPLE DRN',
          symbol: 'AAPL34.BVMF',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'B3 - Brasil Bolsa Balcão S.A',
            acronym: 'Bovespa',
            mic: 'BVMF',
            country: 'Brazil',
            country_code: 'BR',
            city: 'Sao Paulo',
            website: 'www.bmfbovespa.com.br',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL.XSGO',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Santiago Stock Exchange',
            acronym: 'BVS',
            mic: 'XSGO',
            country: 'Chile',
            country_code: 'CL',
            city: 'Santiago',
            website: 'www.bolsadesantiago.com',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL.XBOG',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Bolsa de Valores de Colombia',
            acronym: 'BVC',
            mic: 'XBOG',
            country: 'Colombia',
            country_code: 'CO',
            city: 'Bogota',
            website: 'www.bvc.com.co',
          },
        },
        {
          name: 'APPLE INC. REGISTERED SHARES O.N.',
          symbol: 'APC.XSTU',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Börse Stuttgart',
            acronym: 'XSTU',
            mic: 'XSTU',
            country: 'Germany',
            country_code: 'DE',
            city: 'Stuttgart',
            website: 'www.boerse-stuttgart.de',
          },
        },
        {
          name: 'APPLE INC.',
          symbol: 'APC.XFRA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Deutsche Börse',
            acronym: 'FSX',
            mic: 'XFRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: 'www.deutsche-boerse.com',
          },
        },
        {
          name: 'APPLE INC.',
          symbol: 'APC.XETRA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Deutsche Börse Xetra',
            acronym: 'XETR',
            mic: 'XETRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: '',
          },
        },
        {
          name: 'APPLE',
          symbol: 'AAPL.XMIL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Borsa Italiana',
            acronym: 'MIL',
            mic: 'XMIL',
            country: 'Italy',
            country_code: 'IT',
            city: 'Milano',
            website: 'www.borsaitaliana.it',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL.XMEX',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Mexican Stock Exchange',
            acronym: 'BMV',
            mic: 'XMEX',
            country: 'Mexico',
            country_code: 'MX',
            city: 'Mexico City',
            website: 'www.bmv.com.mx',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL.XLIM',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Bolsa de Valores de Lima',
            acronym: 'BVL',
            mic: 'XLIM',
            country: 'Peru',
            country_code: 'PE',
            city: 'Lima',
            website: 'www.bvl.com.pe',
          },
        },
        {
          name: 'Apple Hospitality REIT Inc',
          symbol: 'APLE',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Apple Flavor Fragrance Group Company Ltd',
          symbol: '603020.XSHG',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Shanghai Stock Exchange',
            acronym: 'SSE',
            mic: 'XSHG',
            country: 'China',
            country_code: 'CN',
            city: 'Shanghai',
            website: 'www.sse.com.cn',
          },
        },
        {
          name: 'APPLE INTERNATIONAL CO LTD',
          symbol: '2788.XTKS',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Tokyo Stock Exchange',
            acronym: 'TSE',
            mic: 'XTKS',
            country: 'Japan',
            country_code: 'JP',
            city: 'Tokyo',
            website: 'www.jpx.co.jp',
          },
        },
        {
          name: 'APPLEGREEN PLC ORD EUR0.01',
          symbol: 'APGN.XLON',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'London Stock Exchange',
            acronym: 'LSE',
            mic: 'XLON',
            country: 'United Kingdom',
            country_code: 'GB',
            city: 'London',
            website: 'www.londonstockexchange.com',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL.XBUE',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'Buenos Aires Stock Exchange',
            acronym: 'BCBA',
            mic: 'XBUE',
            country: 'Argentina',
            country_code: 'AR',
            city: 'Buenos Aires',
            website: 'www.bcba.sba.com.ar',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPLD.XBUE',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Buenos Aires Stock Exchange',
            acronym: 'BCBA',
            mic: 'XBUE',
            country: 'Argentina',
            country_code: 'AR',
            city: 'Buenos Aires',
            website: 'www.bcba.sba.com.ar',
          },
        },
        {
          name: 'Apple Green Holding Inc',
          symbol: 'AGPL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'OTC PINK current',
            acronym: 'PINK',
            mic: 'PINC',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.otcmarkets.com',
          },
        },
        {
          name: 'Apple Rush Company Inc',
          symbol: 'APRU',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'OTC PINK current',
            acronym: 'PINK',
            mic: 'PINC',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.otcmarkets.com',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPL',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Apple Green Holding Inc',
          symbol: 'AGPL',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'APPLE HOSPITALITY REIT INC',
          symbol: 'APLE',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Applegreen plc',
          symbol: 'APGN.XSTU',
          has_intraday: false,
          has_eod: true,
          country: 'Germany',
          stock_exchange: {
            name: 'Börse Stuttgart',
            acronym: 'XSTU',
            mic: 'XSTU',
            country: 'Germany',
            country_code: 'DE',
            city: 'Stuttgart',
            website: 'www.boerse-stuttgart.de',
          },
        },
        {
          name: 'Apple Finance Limited',
          symbol: '500014.XBOM',
          has_intraday: false,
          has_eod: true,
          country: 'India',
          stock_exchange: {
            name: 'Bombay Stock Exchange',
            acronym: 'MSE',
            mic: 'XBOM',
            country: 'India',
            country_code: 'IN',
            city: 'Mumbai',
            website: 'www.bseindia.com',
          },
        },
        {
          name: 'APPLE HOSPITALITY REIT',
          symbol: '48T.XFRA',
          has_intraday: false,
          has_eod: true,
          country: 'Germany',
          stock_exchange: {
            name: 'Deutsche Börse',
            acronym: 'FSX',
            mic: 'XFRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: 'www.deutsche-boerse.com',
          },
        },
        {
          name: 'APPLE INC. CDR',
          symbol: 'APC8.XFRA',
          has_intraday: false,
          has_eod: true,
          country: 'Germany',
          stock_exchange: {
            name: 'Deutsche Börse',
            acronym: 'FSX',
            mic: 'XFRA',
            country: 'Germany',
            country_code: 'DE',
            city: 'Frankfurt',
            website: 'www.deutsche-boerse.com',
          },
        },
        {
          name: 'APPLE DRN',
          symbol: 'AAPL34',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Apple Flavor Fragrance Group Company Ltd',
          symbol: '603020',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'APPLE INC',
          symbol: 'AAPLD',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Apple Rush Comp Inc',
          symbol: 'APRU',
          has_intraday: true,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'Investors Exchange',
            acronym: 'IEX',
            mic: 'IEXG',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.iextrading.com',
          },
        },
        {
          name: 'Apple Inc.',
          symbol: '1AAPL.XMIL',
          has_intraday: false,
          has_eod: true,
          country: 'Italy',
          stock_exchange: {
            name: 'Borsa Italiana',
            acronym: 'MIL',
            mic: 'XMIL',
            country: 'Italy',
            country_code: 'IT',
            city: 'Milano',
            website: 'www.borsaitaliana.it',
          },
        },
      ],
    };

  if (page === 1)
    return {
      pagination: {
        limit: 5,
        offset: 0,
        count: 5,
        total: 25,
      },
      data: [
        {
          name: 'Microsoft Corporation',
          symbol: 'MSFT',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'Apple Inc',
          symbol: 'AAPL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'Amazon.com Inc',
          symbol: 'AMZN',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'Alphabet Inc - Class C',
          symbol: 'GOOG',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'Alphabet Inc - Class A',
          symbol: 'GOOGL',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
      ],
    };

  if (page === 2)
    return {
      pagination: {
        limit: 5,
        offset: 5,
        count: 5,
        total: 25,
      },
      data: [
        {
          name: 'Alibaba Group Holding Ltd',
          symbol: 'BABA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Meta Platforms Inc - Class A',
          symbol: 'FB',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
        {
          name: 'BERKSHIRE HATHAWAY INC',
          symbol: 'BRK.B',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'BERKSHIRE HATHAWAY INC',
          symbol: 'BRK.A',
          has_intraday: false,
          has_eod: false,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Vodafone Group plc',
          symbol: 'VOD',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'NASDAQ Stock Exchange',
            acronym: 'NASDAQ',
            mic: 'XNAS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nasdaq.com',
          },
        },
      ],
    };

  if (page === 3)
    return {
      pagination: {
        limit: 5,
        offset: 10,
        count: 5,
        total: 25,
      },
      data: [
        {
          name: 'Visa Inc - Class A',
          symbol: 'V',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'JPMorgan Chase & Company',
          symbol: 'JPM',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Johnson & Johnson',
          symbol: 'JNJ',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Walmart Inc',
          symbol: 'WMT',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Mastercard Incorporated - Class A',
          symbol: 'MA',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
      ],
    };

  if (page === 4)
    return {
      pagination: {
        limit: 5,
        offset: 15,
        count: 5,
        total: 25,
      },
      data: [
        {
          name: 'Procter & Gamble Company',
          symbol: 'PG',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Taiwan Semiconductor Manufacturing',
          symbol: 'TSM',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Chunghwa Telecom',
          symbol: 'CHT',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'New York Stock Exchange',
            acronym: 'NYSE',
            mic: 'XNYS',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.nyse.com',
          },
        },
        {
          name: 'Roche Holding AG',
          symbol: 'RHHBF',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'OTC Markets',
            acronym: '',
            mic: 'OTCM',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.otcmarkets.com',
          },
        },
        {
          name: 'Roche Holding AG',
          symbol: 'RHHVF',
          has_intraday: false,
          has_eod: true,
          country: null,
          stock_exchange: {
            name: 'OTC Markets',
            acronym: '',
            mic: 'OTCM',
            country: 'USA',
            country_code: 'US',
            city: 'New York',
            website: 'www.otcmarkets.com',
          },
        },
      ],
    };

  return {
    pagination: {
      limit: 5,
      offset: 20,
      count: 5,
      total: 25,
    },
    data: [
      {
        name: 'AT&T Inc',
        symbol: 'T',
        has_intraday: false,
        has_eod: true,
        country: null,
        stock_exchange: {
          name: 'New York Stock Exchange',
          acronym: 'NYSE',
          mic: 'XNYS',
          country: 'USA',
          country_code: 'US',
          city: 'New York',
          website: 'www.nyse.com',
        },
      },
      {
        name: 'Unitedhealth Group Inc',
        symbol: 'UNH',
        has_intraday: false,
        has_eod: true,
        country: null,
        stock_exchange: {
          name: 'New York Stock Exchange',
          acronym: 'NYSE',
          mic: 'XNYS',
          country: 'USA',
          country_code: 'US',
          city: 'New York',
          website: 'www.nyse.com',
        },
      },
      {
        name: 'Bank Of America Corp',
        symbol: 'BAC',
        has_intraday: false,
        has_eod: true,
        country: null,
        stock_exchange: {
          name: 'New York Stock Exchange',
          acronym: 'NYSE',
          mic: 'XNYS',
          country: 'USA',
          country_code: 'US',
          city: 'New York',
          website: 'www.nyse.com',
        },
      },
      {
        name: 'Home Depot Inc',
        symbol: 'HD',
        has_intraday: false,
        has_eod: true,
        country: null,
        stock_exchange: {
          name: 'New York Stock Exchange',
          acronym: 'NYSE',
          mic: 'XNYS',
          country: 'USA',
          country_code: 'US',
          city: 'New York',
          website: 'www.nyse.com',
        },
      },
      {
        name: 'Intel Corp',
        symbol: 'INTC',
        has_intraday: false,
        has_eod: true,
        country: null,
        stock_exchange: {
          name: 'NASDAQ Stock Exchange',
          acronym: 'NASDAQ',
          mic: 'XNAS',
          country: 'USA',
          country_code: 'US',
          city: 'New York',
          website: 'www.nasdaq.com',
        },
      },
    ],
  };
};

export const getTicker = async ({ symbol }: { symbol: string | undefined }) => {
  if (symbol === 'AAPL')
    return {
      name: 'Apple Inc',
      symbol: 'AAPL',
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: 'NASDAQ Stock Exchange',
        acronym: 'NASDAQ',
        mic: 'XNAS',
        country: 'USA',
        country_code: 'US',
        city: 'New York',
        website: 'WWW.NASDAQ.COM',
      },
    };
  if (symbol === 'MSFT')
    return {
      name: 'Microsoft Corporation',
      symbol: 'MSFT',
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: 'NASDAQ Stock Exchange',
        acronym: 'NASDAQ',
        mic: 'XNAS',
        country: 'USA',
        country_code: 'US',
        city: 'New York',
        website: 'WWW.NASDAQ.COM',
      },
    };
  if (symbol === 'AMZN')
    return {
      name: 'Amazon.com Inc',
      symbol: 'AMZN',
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: 'NASDAQ Stock Exchange',
        acronym: 'NASDAQ',
        mic: 'XNAS',
        country: 'USA',
        country_code: 'US',
        city: 'New York',
        website: 'www.nasdaq.com',
      },
    };
  if (symbol?.includes('MSFT34'))
    return {
      name: 'MICROSOFT DRN',
      symbol: 'MSFT34',
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: 'B3 - Brasil Bolsa Balcão S.A',
        acronym: 'Bovespa',
        mic: 'BVMF',
        country: 'Brazil',
        country_code: 'BR',
        city: 'Sao Paulo',
        website: 'WWW.BMFBOVESPA.COM.BR',
      },
    };
  if (symbol?.includes('AAPL34'))
    return {
      name: 'APPLE DRN',
      symbol: 'AAPL34.BVMF',
      has_intraday: false,
      has_eod: true,
      country: null,
      stock_exchange: {
        name: 'B3 - Brasil Bolsa Balcão S.A',
        acronym: 'Bovespa',
        mic: 'BVMF',
        country: 'Brazil',
        country_code: 'BR',
        city: 'Sao Paulo',
        website: 'www.bmfbovespa.com.br',
      },
    };
};

export const getTickerEod = async ({
  symbol,
  date,
}: {
  symbol: string | undefined;
  date?: string | null;
}) => {
  return {
    open: 187.845,
    high: 189.5,
    low: 187.78,
    close: 188.01,
    volume: 53790499.0,
    adj_high: 189.5,
    adj_low: 187.78,
    adj_close: 188.01,
    adj_open: 187.845,
    adj_volume: 53790499.0,
    split_factor: 1.0,
    dividend: 0.0,
    symbol: 'AAPL',
    exchange: 'XNAS',
    date: '2023-11-15T00:00:00+0000',
  };
};

export const getTickerHistorical = async ({
  symbol,
  date_from,
  date_to,
}: {
  symbol: string | undefined;
  date_from: string | null;
  date_to: string | null;
}) => {
  return {
    pagination: {
      limit: 100,
      offset: 0,
      count: 24,
      total: 24,
    },
    data: [
      {
        open: 183.97,
        high: 186.57,
        low: 183.53,
        close: 186.4,
        volume: 66133400.0,
        adj_high: 186.565,
        adj_low: 183.53,
        adj_close: 186.4,
        adj_open: 183.97,
        adj_volume: 66177922.0,
        split_factor: 1.0,
        dividend: 0.24,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-10T00:00:00+0000',
      },
      {
        open: 182.96,
        high: 184.115,
        low: 181.81,
        close: 182.41,
        volume: 53593733.0,
        adj_high: 184.12,
        adj_low: 181.81,
        adj_close: 182.41,
        adj_open: 182.96,
        adj_volume: 53763540.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-09T00:00:00+0000',
      },
      {
        open: 182.35,
        high: 183.45,
        low: 181.599,
        close: 182.89,
        volume: 49214864.0,
        adj_high: 183.45,
        adj_low: 181.59,
        adj_close: 182.89,
        adj_open: 182.35,
        adj_volume: 49340282.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-08T00:00:00+0000',
      },
      {
        open: 179.18,
        high: 182.44,
        low: 178.98,
        close: 181.82,
        volume: 69660972.0,
        adj_high: 182.44,
        adj_low: 178.97,
        adj_close: 181.82,
        adj_open: 179.18,
        adj_volume: 70529966.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-07T00:00:00+0000',
      },
      {
        open: 176.38,
        high: 179.43,
        low: 176.21,
        close: 179.23,
        volume: 58830087.0,
        adj_high: 179.43,
        adj_low: 176.21,
        adj_close: 179.23,
        adj_open: 176.38,
        adj_volume: 63841310.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-06T00:00:00+0000',
      },
      {
        open: 174.24,
        high: 176.82,
        low: 173.35,
        close: 176.65,
        volume: 79763700.0,
        adj_high: 176.82,
        adj_low: 173.35,
        adj_close: 176.65,
        adj_open: 174.24,
        adj_volume: 79829246.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-03T00:00:00+0000',
      },
      {
        open: 175.52,
        high: 177.78,
        low: 175.46,
        close: 177.57,
        volume: 76083900.0,
        adj_high: 177.78,
        adj_low: 175.46,
        adj_close: 177.57,
        adj_open: 175.52,
        adj_volume: 77334752.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-02T00:00:00+0000',
      },
      {
        open: 171.0,
        high: 174.23,
        low: 170.13,
        close: 173.97,
        volume: 56430876.0,
        adj_high: 174.23,
        adj_low: 170.12,
        adj_close: 173.97,
        adj_open: 171.0,
        adj_volume: 56934906.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-11-01T00:00:00+0000',
      },
      {
        open: 169.35,
        high: 170.9,
        low: 167.9,
        close: 170.77,
        volume: 44768914.0,
        adj_high: 170.9,
        adj_low: 167.9,
        adj_close: 170.77,
        adj_open: 169.35,
        adj_volume: 44846017.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-31T00:00:00+0000',
      },
      {
        open: 169.02,
        high: 171.17,
        low: 168.87,
        close: 170.29,
        volume: 51082900.0,
        adj_high: 171.17,
        adj_low: 168.87,
        adj_close: 170.29,
        adj_open: 169.02,
        adj_volume: 51130955.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-30T00:00:00+0000',
      },
      {
        open: 166.91,
        high: 168.96,
        low: 166.83,
        close: 168.22,
        volume: 58468600.0,
        adj_high: 168.96,
        adj_low: 166.83,
        adj_close: 168.22,
        adj_open: 166.91,
        adj_volume: 58499129.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-27T00:00:00+0000',
      },
      {
        open: 170.37,
        high: 171.3775,
        low: 165.67,
        close: 166.89,
        volume: 69970609.0,
        adj_high: 171.3775,
        adj_low: 165.67,
        adj_close: 166.89,
        adj_open: 170.37,
        adj_volume: 70625258.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-26T00:00:00+0000',
      },
      {
        open: 171.88,
        high: 173.06,
        low: 170.65,
        close: 171.1,
        volume: 53296996.0,
        adj_high: 173.06,
        adj_low: 170.65,
        adj_close: 171.1,
        adj_open: 171.88,
        adj_volume: 57156962.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-25T00:00:00+0000',
      },
      {
        open: 173.05,
        high: 173.67,
        low: 171.46,
        close: 173.44,
        volume: 42363324.0,
        adj_high: 173.67,
        adj_low: 171.45,
        adj_close: 173.44,
        adj_open: 173.05,
        adj_volume: 43816644.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-24T00:00:00+0000',
      },
      {
        open: 170.91,
        high: 174.01,
        low: 169.94,
        close: 173.0,
        volume: 55856506.0,
        adj_high: 174.01,
        adj_low: 169.93,
        adj_close: 173.0,
        adj_open: 170.91,
        adj_volume: 55980109.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-23T00:00:00+0000',
      },
      {
        open: 175.31,
        high: 175.42,
        low: 172.64,
        close: 172.88,
        volume: 64189300.0,
        adj_high: 175.42,
        adj_low: 172.64,
        adj_close: 172.88,
        adj_open: 175.31,
        adj_volume: 64244028.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-20T00:00:00+0000',
      },
      {
        open: 176.04,
        high: 177.84,
        low: 175.19,
        close: 175.46,
        volume: 55176703.0,
        adj_high: 177.84,
        adj_low: 175.19,
        adj_close: 175.46,
        adj_open: 176.04,
        adj_volume: 59302863.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-19T00:00:00+0000',
      },
      {
        open: 175.58,
        high: 177.57,
        low: 175.11,
        close: 175.84,
        volume: 54587851.0,
        adj_high: 177.575,
        adj_low: 175.11,
        adj_close: 175.84,
        adj_open: 175.58,
        adj_volume: 54764375.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-18T00:00:00+0000',
      },
      {
        open: 176.645,
        high: 178.42,
        low: 174.8,
        close: 177.15,
        volume: 55881270.0,
        adj_high: 178.42,
        adj_low: 174.8,
        adj_close: 177.15,
        adj_open: 176.645,
        adj_volume: 57549350.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-17T00:00:00+0000',
      },
      {
        open: 176.75,
        high: 179.075,
        low: 176.51,
        close: 178.72,
        volume: 52257826.0,
        adj_high: 179.075,
        adj_low: 176.51,
        adj_close: 178.72,
        adj_open: 176.75,
        adj_volume: 52516984.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-16T00:00:00+0000',
      },
      {
        open: 181.42,
        high: 181.93,
        low: 178.14,
        close: 178.85,
        volume: 51427100.0,
        adj_high: 181.93,
        adj_low: 178.14,
        adj_close: 178.85,
        adj_open: 181.42,
        adj_volume: 51456082.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-13T00:00:00+0000',
      },
      {
        open: 180.07,
        high: 182.34,
        low: 179.04,
        close: 180.71,
        volume: 56608967.0,
        adj_high: 182.34,
        adj_low: 179.04,
        adj_close: 180.71,
        adj_open: 180.07,
        adj_volume: 56743119.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-12T00:00:00+0000',
      },
      {
        open: 178.2,
        high: 179.85,
        low: 177.6,
        close: 179.8,
        volume: 47125074.0,
        adj_high: 179.85,
        adj_low: 177.6,
        adj_close: 179.8,
        adj_open: 178.2,
        adj_volume: 47551098.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-11T00:00:00+0000',
      },
      {
        open: 178.1,
        high: 179.72,
        low: 177.95,
        close: 178.39,
        volume: 42686493.0,
        adj_high: 179.72,
        adj_low: 177.95,
        adj_close: 178.39,
        adj_open: 178.1,
        adj_volume: 43698019.0,
        split_factor: 1.0,
        dividend: 0.0,
        symbol: 'AAPL',
        exchange: 'XNAS',
        date: '2023-10-10T00:00:00+0000',
      },
    ],
  };
};
