import { Github } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { LogoutButton } from "./_components/LogoutButton";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-5 px-4 py-2 border-b border-slate-500 w-full justify-between items-baseline">
          <h1 className="text-2xl font-bold">
            <Link href="/">The broker</Link>
          </h1>
          <h2 className="italic grow">
            A minimalist UI for the stock market info
          </h2>
          <div className="flex items-center gap-4">
            <Link
              href="https://github.com/alexserver/thebroker"
              target="_blank"
            >
              view on github
              <Github className="w-5 h-5 inline-block ml-2" />
            </Link>
            <LogoutButton />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
